### ISSUE TITLE
Does not list all dependencies

### ISSUE THREAD

**Issue by xantares** [LRN/ntldd#3]
Hello,

It seems your tool misses some dlls:
```
$ ./ntldd.exe /usr/i686-w64-mingw32/bin/Qt5Network.dll 
        Qt5Core.dll => Z:\usr\i686-w64-mingw32\bin\Qt5Core.dll (0x0000000000800000)
        ADVAPI32.dll => not found
        CRYPT32.dll => not found
        DNSAPI.dll => not found
        libgcc_s_sjlj-1.dll => Z:\usr\i686-w64-mingw32\bin\libgcc_s_sjlj-1.dll (0x0000000000340000)
        IPHLPAPI.DLL => not found
        KERNEL32.dll => not found
        msvcrt.dll => not found
        libstdc++-6.dll => Z:\usr\i686-w64-mingw32\bin\libstdc++-6.dll (0x0000000000ce0000)
        WS2_32.dll => not found
        zlib1.dll => Z:\usr\i686-w64-mingw32\bin\zlib1.dll (0x0000000000340000)
```

I noticed because I'm working on a similar tool in Python (https://github.com/xantares/mingw-ldd):
```
$ python dependency.py /usr/i686-w64-mingw32/bin/Qt5Network.dll
Arch = i386
Using default prefix /usr/i686-w64-mingw32/bin
/usr/i686-w64-mingw32/bin/Qt5Core.dll
/usr/i686-w64-mingw32/bin/libgcc_s_sjlj-1.dll
/usr/i686-w64-mingw32/bin/libwinpthread-1.dll
/usr/i686-w64-mingw32/bin/libiconv-2.dll
/usr/i686-w64-mingw32/bin/libpcre2-16-0.dll
/usr/i686-w64-mingw32/bin/libstdc++-6.dll
/usr/i686-w64-mingw32/bin/zlib1.dll
The following dependencies not found: 
ADVAPI32.dll
KERNEL32.dll
msvcrt.dll
MPR.DLL
NETAPI32.dll
ole32.dll
SHELL32.dll
USER32.dll
USERENV.dll
VERSION.dll
WINMM.DLL
WS2_32.dll
CRYPT32.dll
DNSAPI.dll
IPHLPAPI.DLL
```

For very complex cases it misses a whole lot more.

**Comment by LRN** [comment]
I've seen something similar when mixing x86 and x86_64 - due to the way c:\windows\system32 gets resolved at runtime, it's possible to end up with c:\windows\system32 (the real one) in your PATH instead of c:\windows\syswow64 (which is what you need for x86 DLL detection to work). Or vice versa.

I'm not developing this project actively right now, but i am willing to merge a patch, if you make one.

**Comment by roytam1** [comment]
> It seems your tool misses some dlls:
> 
> ```
> $ ./ntldd.exe /usr/i686-w64-mingw32/bin/Qt5Network.dll 
>         Qt5Core.dll => Z:\usr\i686-w64-mingw32\bin\Qt5Core.dll (0x0000000000800000)
>         ADVAPI32.dll => not found
>         CRYPT32.dll => not found
>         DNSAPI.dll => not found
>         libgcc_s_sjlj-1.dll => Z:\usr\i686-w64-mingw32\bin\libgcc_s_sjlj-1.dll (0x0000000000340000)
>         IPHLPAPI.DLL => not found
>         KERNEL32.dll => not found
>         msvcrt.dll => not found
>         libstdc++-6.dll => Z:\usr\i686-w64-mingw32\bin\libstdc++-6.dll (0x0000000000ce0000)
>         WS2_32.dll => not found
>         zlib1.dll => Z:\usr\i686-w64-mingw32\bin\zlib1.dll (0x0000000000340000)
> ```

seem that you're running 64bit ntldd on 32bit DLL.
I added some code to deal with this: https://github.com/roytam1/ntldd/commit/0b267dc9836099fda16aace721c7cc346cc060de
but SxS related issue is not fixed by that commit.
